convert -resize 30% car_1.png small30/car_1.png
convert -resize 30% car_2.png small30/car_2.png
convert -resize 30% car_3.png small30/car_3.png
convert -resize 30% car_4.png small30/car_4.png
convert -resize 30% heat_map.png small30/heat_map.png
convert -resize 30% hot_windows.png small30/hot_windows.png
convert -resize 30% labels.png small30/labels.png
convert -resize 30% non-car_1.png small30/non-car_1.png
convert -resize 30% non-car_2.png small30/non-car_2.png
convert -resize 30% non-car_3.png small30/non-car_3.png
convert -resize 30% non-car_4.png small30/non-car_4.png
convert -resize 30% placeholder_project_collage4.png small30/placeholder_project_collage4.png
convert -resize 30% placeholder_project_output.png small30/placeholder_project_output.png
convert -resize 30% result.png small30/result.png
convert -resize 30% search_window_00.png small30/search_window_00.png
convert -resize 30% search_window_75.png small30/search_window_75.png
convert -resize 30% test1_hog.png small30/test1_hog.png
convert -resize 30% test1.jpg small30/test1.jpg
