convert -resize 50% car_1.png small50/car_1.png
convert -resize 50% car_2.png small50/car_2.png
convert -resize 50% car_3.png small50/car_3.png
convert -resize 50% car_4.png small50/car_4.png
convert -resize 50% heat_map.png small50/heat_map.png
convert -resize 50% hot_windows.png small50/hot_windows.png
convert -resize 50% labels.png small50/labels.png
convert -resize 50% non-car_1.png small50/non-car_1.png
convert -resize 50% non-car_2.png small50/non-car_2.png
convert -resize 50% non-car_3.png small50/non-car_3.png
convert -resize 50% non-car_4.png small50/non-car_4.png
convert -resize 50% placeholder_project_collage4.png small50/placeholder_project_collage4.png
convert -resize 50% placeholder_project_output.png small50/placeholder_project_output.png
convert -resize 50% result.png small50/result.png
convert -resize 50% search_window_00.png small50/search_window_00.png
convert -resize 50% search_window_75.png small50/search_window_75.png
convert -resize 50% test1_hog.png small50/test1_hog.png
convert -resize 50% test1.jpg small50/test1.jpg
